name: client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  audio_waveforms: ^1.3.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  file_picker: ^9.2.0
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  http: ^1.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5

flutter:

  uses-material-design: true
